services:
  - type: web
    name: football-database-tracker-v2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn payatas.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
